services:
- docker
language: go
dist: xenial
go:
- 1.12.x
env:
  global:
  - PATH=/home/travis/gopath/bin:$PATH
install:
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make clean
- make test
- make build
branches:
  only:
    - master
